# Generated by Django 5.2.3 on 2025-06-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_booking_special_request_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_logo',
            field=models.ImageField(blank=True, null=True, upload_to='hotel/'),
        ),
    ]
