# Generated by Django 5.2.3 on 2025-06-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_amenity_roomtype_image_remove_roomtype_amenities_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amenity',
            new_name='RoomAmenity',
        ),
    ]
