# Generated by Django 5.2.3 on 2025-06-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_rename_amenity_roomamenity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='base_price',
            field=models.CharField(max_length=300),
        ),
    ]
