# Generated by Django 5.2.3 on 2025-06-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_hotelamenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelamenity',
            name='icon_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
