# Generated by Django 5.2.3 on 2025-06-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_roomtype_display_price_alter_roomtype_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomamenity',
            name='icon_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
